# Generated by Django 5.0.1 on 2025-03-30 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_team_problem_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_member1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_member2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_member3',
        ),
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
